AWSTemplateFormatVersion: '2010-09-09'
Description: "Lambda function supporting AWS Config Resource Compliance Dashboard (CRCD) v2"

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Athena Configuration"
        Parameters:
          - AthenaWorkgroup
          - AthenaDatabaseName
          - AthenaQueryResultBucketName
          - AthenaConfigSnapshotsTableName
      -
        Label:
          default: "AWS Config Logging"
        Parameters:
          - ConfigLoggingBucketArn
          - ConfigLoggingAccountID

    ParameterLabels:
      AthenaWorkgroup:
        default: "Athena Workgroup"
      AthenaDatabaseName:
        default: "Athena Database"
      AthenaQueryResultBucketName:
        default: "Athena query results bucket"
      AthenaConfigSnapshotsTableName:
        default: "Athena table for AWS Config data"
      ConfigLoggingBucketArn:
        default: "Config Bucket ARN"
      ConfigLoggingAccountID:
        default: "Config bucket account"

Parameters:
  ConfigLoggingBucketArn:
    Type: "String"
    Default: "arn:aws:s3:::your-config-bucket"
    Description: "ARN of the S3 bucket that collects AWS Config data"

  ConfigLoggingAccountID:
    Type: "String"
    Default: "1234-1234-1234"
    Description: "AWS Account ID that contains the bucket holding AWS Config snapshots"


  AthenaDatabaseName:
    Type: "String"
    Default: "cid_config_athena_database" 
    Description: "The Athena database for the CID-CRCD dashboard"

  AthenaQueryResultBucketName:
    Type: "String"
    Default: "configathenaresults767398150443" 
    Description: "The Athena Query Result bucket for the workgroup"

  AthenaWorkgroup:
    Type: "String"
    Default: "cid-config-athena-workgroup"
    Description: "The Athena workgroup for the CID-CRCD dashboard"

  AthenaConfigSnapshotsTableName:
    Type: "String"
    Default: "aws_config_configuration_snapshots"
    Description: "The Athena table that contains the AWS Config data for the dashboard"


Resources:
  IAMManagedPolicyLambdaCIDCRCDGlue:
    Type: "AWS::IAM::ManagedPolicy"
    DeletionPolicy: "Delete"
    UpdateReplacePolicy: "Delete"
    Properties:
      ManagedPolicyName: "cid-crcd-glue-policy"
      Path: "/"
      Description: "CID-CRCD Dashboard - Policy that gives Glue permissions to CID-CRCD Lambda execution role"
      Groups: []
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Resource:
          - !Sub "arn:${AWS::Partition}:glue:${AWS::Region}:${AWS::AccountId}:table/{AthenaDatabaseName}/*"
          - !Sub "arn:${AWS::Partition}:glue:${AWS::Region}:${AWS::AccountId}:table/{AthenaDatabaseName}"
          - !Sub "arn:${AWS::Partition}:glue:${AWS::Region}:${AWS::AccountId}:catalog"
          Action:
          - "glue:UpdatePartition"
          - "glue:GetTables"
          - "glue:GetTable"
          - "glue:GetPartitions"
          - "glue:GetPartition"
          - "glue:DeletePartition"
          - "glue:CreatePartition"
          - "glue:BatchGetPartition"
          - "glue:BatchDeletePartition"
          - "glue:BatchCreatePartition"
          Effect: "Allow"
          Sid: "Glue"
      Roles:
      - "cid-crcd-lambda-execution-role"
      Users: []

  IAMManagedPolicyLambdaCIDCRCDS3:
    Type: "AWS::IAM::ManagedPolicy"
    DeletionPolicy: "Delete"
    UpdateReplacePolicy: "Delete"
    Properties:
      ManagedPolicyName: "cid-crcd-s3-policy"
      Path: "/"
      Description: "CID-CRCD Dashboard - Policy that gives permissions on Athena query results S3 bucket to CID-CRCD Lambda execution role"
      Groups: []
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Resource:
          - !Sub "arn:${AWS::Partition}:s3:::{AthenaQueryResultBucketName}"
          - !Sub "arn:${AWS::Partition}:s3:::{AthenaQueryResultBucketName}/*"
          Action:
          - "s3:PutObject"
          - "s3:ListMultipartUploadParts"
          - "s3:ListBucket"
          - "s3:GetObject"
          - "s3:GetBucketLocation"
          Effect: "Allow"
          Sid: "S3"
      Roles:
      - "cid-crcd-lambda-execution-role"
      Users: []

  IAMManagedPolicyLambdaCIDCRCDCloudWatchLogs:
    Type: "AWS::IAM::ManagedPolicy"
    DeletionPolicy: "Delete"
    UpdateReplacePolicy: "Delete"
    Properties:
      ManagedPolicyName: "cid-crcd-cloudwatch-logs-policy"
      Path: "/"
      Description: "CID-CRCD Dashboard - Policy that gives CloudWatch Logs permissions to CID-CRCD Lambda execution role"
      Groups: []
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Resource: !Sub "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/lambda-cid-crcd-config:*"
          Action:
          - "logs:PutLogEvents"
          - "logs:CreateLogStream"
          - "logs:CreateLogGroup"
          Effect: "Allow"
          Sid: "CloudWatchLogGroup"
      Roles:
      - "cid-crcd-lambda-execution-role"
      Users: []

  IAMManagedPolicyLambdaCIDCRCDAthena:
    Type: "AWS::IAM::ManagedPolicy"
    DeletionPolicy: "Delete"
    UpdateReplacePolicy: "Delete"
    Properties:
      ManagedPolicyName: "cid-crcd-athena-policy"
      Path: "/"
      Description: "CID-CRCD Dashboard - Policy that gives Athena permissions to CID-CRCD Lambda execution role"
      Groups: []
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Resource: !Sub "arn:${AWS::Partition}:athena:${AWS::Region}:${AWS::AccountId}:workgroup/{AthenaWorkgroup}"
          Action:
          - "athena:StartQueryExecution"
          - "athena:GetQueryExecution"
          Effect: "Allow"
          Sid: "AthenaAccess"
      Roles:
      - "cid-crcd-lambda-execution-role"
      Users: []

  LambdaFunctionCIDCRCDConfig:
    Type: "AWS::Lambda::Function"
    DeletionPolicy: "Delete"
    UpdateReplacePolicy: "Delete"
    Properties:
      FunctionName: "cid-crcd-config-snapshot-partitioner"
      Description: "CID-CRCD Dashboard - Lambda function that adds partitions when there are new AWS Config Snapshots events"
      MemorySize: 128
      EphemeralStorage:
        Size: 512
      Timeout: 300
      Runtime: "python3.12"
      Architectures:
        - "x86_64"
      TracingConfig:
        Mode: "Active"
      VpcConfig:
        SecurityGroupIds: []
        SubnetIds: []
        Ipv6AllowedForDualStack: false
      RuntimeManagementConfig:
        UpdateRuntimeOn: "Auto"
      Handler: "lambda_function.lambda_handler"
      ReservedConcurrentExecutions: 1
      Role:
        Fn::GetAtt:
        - "IAMRoleLambdaCIDCRCDConfig"
        - "Arn"
      FileSystemConfigs: []
      LoggingConfig:
        LogFormat: "Text"
        LogGroup: "/aws/lambda/lambda-cid-crcd-config"
      Environment:
        Variables:
          ATHENA_DATABASE_NAME: !Ref AthenaDatabaseName
          ATHENA_QUERY_RESULTS_BUCKET_NAME: !Ref AthenaQueryResultBucketName
          ATHENA_WORKGROUP: !Ref AthenaWorkgroup
          CONFIG_TABLE_NAME: !Ref AthenaConfigSnapshotsTableName
          # TODO: Refactor the lambda code and remove this variable. It's the region where the function is deployed anyway
          ATHENA_REGION: !Ref AWS::Region
      Code:
        # TODO: handle the code
        ZipFile: | 
          def lambda_handler(event, context):
            print("Hello Lambda!")
            return "Lambda is done"
        
  IAMRoleLambdaCIDCRCDConfig:
    # Allows to add partitions to Athena and Glue, send logs to Cloudwatch, access S3 to read objects, defined in separate policies
    Type: "AWS::IAM::Role"
    DeletionPolicy: "Delete"
    UpdateReplacePolicy: "Delete"
    Properties:
      Path: "/"
      ManagedPolicyArns:
      - Ref: "IAMManagedPolicyLambdaCIDCRCDAthena"
      - Ref: "IAMManagedPolicyLambdaCIDCRCDGlue"
      - Ref: "IAMManagedPolicyLambdaCIDCRCDS3"
      - Ref: "IAMManagedPolicyLambdaCIDCRCDCloudWatchLogs"
      MaxSessionDuration: 3600
      RoleName: "cid-crcd-lambda-execution-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Action: "sts:AssumeRole"
          Effect: "Allow"
          Principal:
            Service: "lambda.amazonaws.com"
          Sid: ""

  # Allows the S3 bucket that contains the Config Snapshots to invoke the lambda function
  # The S3 bucket must be manually configured, too
  LambdaPermissionLambdaCIDCRCDInvocationPermission:
    Type: "AWS::Lambda::Permission"
    DeletionPolicy: "Delete"
    UpdateReplacePolicy: "Delete"
    Properties:
      FunctionName:
        Fn::GetAtt:
        - "LambdaFunctionCIDCRCDConfig"
        - "Arn"
      Action: "lambda:InvokeFunction"
      SourceArn: !Ref ConfigLoggingBucketArn
      Principal: "s3.amazonaws.com"
      SourceAccount: !Ref ConfigLoggingAccountID

Outputs:
  LambdaARN:
    Description: "ARN of the Lambda function supporting CID-CRCD Dashboard"
    Value:
      Fn::GetAtt:
        - "LambdaFunctionCIDCRCDConfig"
        - "Arn"