AWSTemplateFormatVersion: '2010-09-09'
Description: "Lambda function supporting AWS Config Resource Compliance Dashboard (CRCD) v2"

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Athena Configuration"
        Parameters:
          - AthenaWorkgroup
          - AthenaDatabaseName
          - AthenaQueryResultBucketName
          - AthenaConfigSnapshotsTableName
      -
        Label:
          default: "AWS Config Logging"
        Parameters:
          - ConfigLoggingBucketArn
          - ConfigLoggingAccountID

    ParameterLabels:
      AthenaWorkgroup:
        default: "Athena Workgroup"
      AthenaDatabaseName:
        default: "Athena Database"
      AthenaQueryResultBucketName:
        default: "Athena query results bucket"
      AthenaConfigSnapshotsTableName:
        default: "Athena table for AWS Config data"
      ConfigLoggingBucketArn:
        default: "Config bucket ARN"
      ConfigLoggingAccountID:
        default: "Config bucket account"

# TODO match parameters with the default values by cid-cmd tool
Parameters:
  ConfigLoggingBucketArn:
    Type: "String"
    Default: "arn:aws:s3:::your-config-bucket"
    Description: "ARN of the S3 bucket that collects AWS Config data"
    AllowedPattern: '^arn:(aws|aws-cn|aws-us-gov):s3:::[a-z0-9][a-z0-9-]{1,61}[a-z0-9]$'
    ConstraintDescription: "Required"

  ConfigLoggingAccountID:
    Type: "String"
    Default: "123412341234"
    Description: "AWS Account ID that contains the bucket holding AWS Config snapshots"
    MaxLength: 12
    MinLength: 12
    AllowedPattern: '^\d{12}$'
    ConstraintDescription: "Required"

  AthenaDatabaseName:
    Type: "String"
    Default: "cid-crcd-athena-database"
    Description: "The Athena database for the CID-CRCD dashboard"
    MinLength: 1
    ConstraintDescription: "Required"

  AthenaQueryResultBucketName:
    Type: "String"
    Default: "cid-crcd-athenaresults" 
    Description: "The Athena query result bucket for the workgroup"
    MinLength: 1
    ConstraintDescription: "Required"

  AthenaWorkgroup:
    Type: "String"
    Default: "cid-crcd-athena-workgroup"
    Description: "The Athena workgroup for the CID-CRCD dashboard"
    MinLength: 1
    ConstraintDescription: "Required"

  AthenaConfigSnapshotsTableName:
    Type: "String"
    Default: "cid-crcd-configuration-snapshots"
    Description: "The Athena table that contains the AWS Config data for the dashboard"
    MinLength: 1
    ConstraintDescription: "Required"

Rules:
  MandatoryConfigLoggingBucketArn:
    Assertions:
      - Assert: !Not 
        - !Equals 
          - !Ref ConfigLoggingBucketArn
          - ''
        AssertDescription: "Config bucket ARN is required"
  MandatoryConfigLoggingAccountID:
    Assertions:
      - Assert: !Not 
        - !Equals 
          - !Ref ConfigLoggingAccountID
          - ''
        AssertDescription: "Config bucket account is required"
  MandatoryAthenaDatabaseName:
    Assertions:
      - Assert: !Not 
        - !Equals 
          - !Ref AthenaDatabaseName
          - ''
        AssertDescription: "Athena database is required"
  MandatoryAthenaQueryResultBucketName:
    Assertions:
      - Assert: !Not 
        - !Equals 
          - !Ref AthenaQueryResultBucketName
          - ''
        AssertDescription: "Athena query result bucket is required"
  MandatoryAthenaWorkgroup:
    Assertions:
      - Assert: !Not 
        - !Equals 
          - !Ref AthenaWorkgroup
          - ''
        AssertDescription: "Athena workgroup is required"
  MandatoryAthenaConfigSnapshotsTableName:
    Assertions:
      - Assert: !Not 
        - !Equals 
          - !Ref AthenaConfigSnapshotsTableName
          - ''
        AssertDescription: "Athena table is required"

# TODO policy names must be globally unique, end them with the region
Resources:
  IAMManagedPolicyLambdaCIDCRCDGlue:
    Type: "AWS::IAM::ManagedPolicy"
    DeletionPolicy: "Delete"
    UpdateReplacePolicy: "Delete"
    Properties:
      ManagedPolicyName: "cid-crcd-glue-policy"
      Path: "/"
      Description: "CID-CRCD Dashboard - Policy that gives Glue permissions to CID-CRCD Lambda execution role"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Resource:
          - !Sub "arn:${AWS::Partition}:glue:${AWS::Region}:${AWS::AccountId}:table/${AthenaDatabaseName}/*"
          - !Sub "arn:${AWS::Partition}:glue:${AWS::Region}:${AWS::AccountId}:table/${AthenaDatabaseName}"
          - !Sub "arn:${AWS::Partition}:glue:${AWS::Region}:${AWS::AccountId}:catalog"
          Action:
          - "glue:UpdatePartition"
          - "glue:GetTables"
          - "glue:GetTable"
          - "glue:GetPartitions"
          - "glue:GetPartition"
          - "glue:DeletePartition"
          - "glue:CreatePartition"
          - "glue:BatchGetPartition"
          - "glue:BatchDeletePartition"
          - "glue:BatchCreatePartition"
          Effect: "Allow"
          Sid: "GluePartitions"

  IAMManagedPolicyLambdaCIDCRCDS3:
    Type: "AWS::IAM::ManagedPolicy"
    DeletionPolicy: "Delete"
    UpdateReplacePolicy: "Delete"
    Properties:
      ManagedPolicyName: "cid-crcd-s3-athenaqueryresults-policy"
      Path: "/"
      Description: "CID-CRCD Dashboard - Policy that gives permissions on Athena query results S3 bucket to CID-CRCD Lambda execution role"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Resource:
          - !Sub "arn:${AWS::Partition}:s3:::${AthenaQueryResultBucketName}"
          - !Sub "arn:${AWS::Partition}:s3:::${AthenaQueryResultBucketName}/*"
          Action:
          - "s3:PutObject"
          - "s3:ListMultipartUploadParts"
          - "s3:ListBucket"
          - "s3:GetObject"
          - "s3:GetBucketLocation"
          Effect: "Allow"
          Sid: "S3AthenaQueryResults"

  IAMManagedPolicyLambdaCIDCRCDS3TriggerObject:
    Type: "AWS::IAM::ManagedPolicy"
    DeletionPolicy: "Delete"
    UpdateReplacePolicy: "Delete"
    Properties:
      ManagedPolicyName: "cid-crcd-s3-triggerobject-policy"
      Path: "/"
      Description: "CID-CRCD Dashboard - Policy that allows CID-CRCD Lambda to receive objects from the Config S3 bucket"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Resource:
          - !Ref ConfigLoggingBucketArn
          Action:
          - "s3:GetObject"
          # TODO added those below manually on the policy
          - "s3:ListBucket"
          - "s3:ListBucketVersions"
          - "s3:GetObjectVersion"
          - "s3:GetLifecycleConfiguration"
          Effect: "Allow"
          Sid: "S3ConfigSnapshotObject"

  IAMManagedPolicyLambdaCIDCRCDCloudWatchLogs:
    Type: "AWS::IAM::ManagedPolicy"
    DeletionPolicy: "Delete"
    UpdateReplacePolicy: "Delete"
    Properties:
      ManagedPolicyName: "cid-crcd-cloudwatch-logs-policy"
      Path: "/"
      Description: "CID-CRCD Dashboard - Policy that gives CloudWatch Logs permissions to CID-CRCD Lambda execution role"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Resource: !Sub "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/cid-crcd-lambda-partitioner:*"
          Action:
          - "logs:PutLogEvents"
          - "logs:CreateLogStream"
          - "logs:CreateLogGroup"
          Effect: "Allow"
          Sid: "CloudWatchLogGroup"

  IAMManagedPolicyLambdaCIDCRCDAthena:
    Type: "AWS::IAM::ManagedPolicy"
    DeletionPolicy: "Delete"
    UpdateReplacePolicy: "Delete"
    Properties:
      ManagedPolicyName: "cid-crcd-athena-policy"
      Path: "/"
      Description: "CID-CRCD Dashboard - Policy that gives Athena permissions to CID-CRCD Lambda execution role"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Resource: !Sub "arn:${AWS::Partition}:athena:${AWS::Region}:${AWS::AccountId}:workgroup/${AthenaWorkgroup}"
          Action:
          - "athena:StartQueryExecution"
          - "athena:GetQueryExecution"
          Effect: "Allow"
          Sid: "AthenaAccess"

  LambdaFunctionCIDCRCDConfig:
    Type: "AWS::Lambda::Function"
    DeletionPolicy: "Delete"
    UpdateReplacePolicy: "Delete"
    Properties:
      FunctionName: "cid-crcd-config-snapshot-partitioner"
      Description: "CID-CRCD Dashboard - Lambda function that adds partitions when there are new AWS Config Snapshots events"
      MemorySize: 128
      EphemeralStorage:
        Size: 512
      Timeout: 300
      Runtime: "python3.12"
      Architectures:
        - "x86_64"
      TracingConfig:
        Mode: "Active"
      VpcConfig:
        SecurityGroupIds: []
        SubnetIds: []
        Ipv6AllowedForDualStack: false
      RuntimeManagementConfig:
        UpdateRuntimeOn: "Auto"
      # TODO the file name from the code below will be called index.py once you open it in Lambda
      Handler: "index.lambda_handler"
      ReservedConcurrentExecutions: 1
      Role:
        Fn::GetAtt:
        - "IAMRoleLambdaCIDCRCDConfig"
        - "Arn"
      FileSystemConfigs: []
      LoggingConfig:
        LogFormat: "Text"
        # this is already by default LogGroup: "/aws/lambda/cid-crcd-config-snapshot-partitioner"
      Environment:
        Variables:
          ATHENA_DATABASE_NAME: !Ref AthenaDatabaseName
          ATHENA_QUERY_RESULTS_BUCKET_NAME: !Ref AthenaQueryResultBucketName
          ATHENA_WORKGROUP: !Ref AthenaWorkgroup
          CONFIG_TABLE_NAME: !Ref AthenaConfigSnapshotsTableName
          # TODO: Refactor the lambda code and remove this variable. It's the region where the function is deployed anyway
          ATHENA_REGION: !Ref AWS::Region
      Code:
        # TODO: handle the code
        ZipFile: | 
          import json
          import urllib.parse
          import boto3
          
          print('Loading function')
          s3 = boto3.client('s3')

          def lambda_handler(event, context):
            print("Received event: " + json.dumps(event, indent=2))
            
            # Get the object from the event and show its content type
            bucket = event['Records'][0]['s3']['bucket']['name']

            key = urllib.parse.unquote_plus(event['Records'][0]['s3']['object']['key'], encoding='utf-8')

            try:
              response = s3.get_object(Bucket=bucket, Key=key)
              print("CONTENT TYPE: " + response['ContentType'])
              return response['ContentType']
            
            except Exception as e:
              print(e)
              print('Error getting object {} from bucket {}. Make sure they exist and your bucket is in the same region as this function.'.format(key, bucket))
              raise e
        
  IAMRoleLambdaCIDCRCDConfig:
    Type: "AWS::IAM::Role"
    DeletionPolicy: "Delete"
    UpdateReplacePolicy: "Delete"
    Description: "CID-CRCD Dashboard - Allows to add partitions to Athena and Glue, send logs to Cloudwatch, access Athena query results S3 bucket, receive objects from Config bucket. Each defined in separate policies"
    Properties:
      Path: "/"
      ManagedPolicyArns:
      - Ref: "IAMManagedPolicyLambdaCIDCRCDAthena"
      - Ref: "IAMManagedPolicyLambdaCIDCRCDGlue"
      - Ref: "IAMManagedPolicyLambdaCIDCRCDS3"
      - Ref: "IAMManagedPolicyLambdaCIDCRCDCloudWatchLogs"
      - Ref: "IAMManagedPolicyLambdaCIDCRCDS3TriggerObject"
      MaxSessionDuration: 3600
      RoleName: "cid-crcd-lambda-execution-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Action: "sts:AssumeRole"
          Effect: "Allow"
          Principal:
            Service: "lambda.amazonaws.com"
          Sid: ""

  # Allows the S3 bucket that contains the Config Snapshots to invoke the lambda function
  LambdaPermissionLambdaCIDCRCDInvocationPermission:
    Type: "AWS::Lambda::Permission"
    DeletionPolicy: "Delete"
    UpdateReplacePolicy: "Delete"
    Properties:
      FunctionName:
        Fn::GetAtt:
        - "LambdaFunctionCIDCRCDConfig"
        - "Arn"
      Action: "lambda:InvokeFunction"
      SourceArn: !Ref ConfigLoggingBucketArn
      Principal: "s3.amazonaws.com"
      SourceAccount: !Ref ConfigLoggingAccountID

Outputs:
  LambdaARN:
    Description: "ARN of the Lambda function supporting CID-CRCD Dashboard"
    Value:
      Fn::GetAtt:
        - "LambdaFunctionCIDCRCDConfig"
        - "Arn"