AWSTemplateFormatVersion: '2010-09-09'
Description: Deployment of AWS Config Resource Compliance Dashboard (CRCD) v2

Parameters:
  lluccParameterExample:
    Type: String
    Default: ''
    Description: Leave Empty / this is not used, todo delete - now changed


Resources:

  CRDCAthenaQueryResultsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::Partition}-llucc-athena-query-results-cid-crcd-${AWS::AccountId}-${AWS::Region}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      AccessControl: BucketOwnerFullControl
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteContent
            Status: 'Enabled'
            ExpirationInDays: 7
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            # todo this is copied from CID CloudFormation template
            - W3045 # Consider using AWS::S3::BucketPolicy instead of AccessControl; standard Athena results setup

  CRDCAthenaWorkgroup: # Athena workgroup to execute CID-CRCD queries with its own result bucket
    Type: AWS::Athena::WorkGroup
    Properties:
      Name: 'llucc-athena-workgroup'
      Description: 'Used for AWS Config Resource Compliance Dashboard (CRCD)'
      WorkGroupConfiguration:
        EnforceWorkGroupConfiguration: true
        ResultConfiguration:
          EncryptionConfiguration:
            EncryptionOption: SSE_S3
          OutputLocation: !Sub 's3://${CRDCAthenaQueryResultsBucket}/'
       

Outputs:
  AthenaWorkgroupName:
    # todo, how to return CRDCAthenaWorkgroup.Name? it says this is not a read only property and fails the CF template
    Description: 'Name of the Athena Workgroup'
    Value: 'This is a sample output'