AWSTemplateFormatVersion: '2010-09-09'
Description: Create an S3 bucket with event notification to a Lambda function

Resources:

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-bucket-gflshruikhdghudhgu
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: ""
                  - Name: suffix
                    Value: ""
            Function: !GetAtt LambdaFunction.Arn

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: my-lambda-dfsgre7854tnjhb
      Runtime: python3.9
      Handler: index.lambda_handler
      Code:
        ZipFile: |
          def lambda_handler(event, context):
            print(event)
            return {
                'statusCode': 200,
                'body': 'S3 event notification received'
            }
      Role: !GetAtt LambdaRole.Arn

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt LambdaFunction.Arn
      Action: 'lambda:InvokeFunction'
      Principal: s3.amazonaws.com
      SourceArn: !GetAtt S3Bucket.Arn

Outputs:
  BucketName:
    Description: Name of the S3 bucket
    Value: !Ref S3Bucket