AWSTemplateFormatVersion: '2010-09-09'
Description: 'CRCD Dashboard - StackSet for deploying CRCD CIRT AWS Config Conformance Pack on all member accounts - RUN in the AWS Organizations management account'

Parameters:
  ConformancePackTemplateUrl:
    Type: String
    Description: 'S3 URL of the conformance pack template from management account'
    
  CentralizedConfigBucket:
    Type: String
    Description: 'Name of the centralized S3 bucket in Log Archive account for AWS Config data'

Resources:
  ConformancePack:
    Type: 'AWS::Config::ConformancePack'
    Properties:
      ConformancePackName: 'crcd-cirt-security-recommendations'
      TemplateS3Uri: !Ref ConformancePackTemplateUrl
      DeliveryS3Bucket: !Ref CentralizedConfigBucket

