# DEPRECATED do not use
# This works, but needs to be created in every region of the AWS Config delegated admin
# It creates a bucket per region, to contain the YAML template of the conformance pack, which is redundant
AWSTemplateFormatVersion: '2010-09-09'
Description: 'CRCD Dashboard - AWS Customer Incident Response Team (CIRT) recommended Conformance Pack deployment - RUN in the AWS Organizations management account'

Parameters:
  ExcludedAccounts:
    Type: CommaDelimitedList
    Description: "Comma-separated list of account IDs to exclude from conformance pack deployment (e.g., '111111111111,222222222222')"
    Default: ""  # Empty default value

Resources:
  # S3 Bucket in management account to store conformance pack template
  DeliveryS3Bucket:
  # checkov:skip=CKV_AWS_18: No need to have access logging on this bucket
    Type: 'AWS::S3::Bucket'
    Properties:
      # TODO do I really need so many buckets, one per account/region?
      # for now I launch this in every region so I need -${AWS::Region} 
      BucketName: !Sub 'awsconfigconforms-crcd-cirt-${AWS::AccountId}-${AWS::Region}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'AES256'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled

  DeliveryS3BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref DeliveryS3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AWSConfigConformsCheckAcls
            Action: s3:GetBucketAcl
            Effect: Allow
            Resource: !GetAtt DeliveryS3Bucket.Arn
            Principal:
              Service: config.amazonaws.com
              # AWS: "*" - this makes it look like it's a public bucket... Resource handler returned message: "User: arn:aws:sts::571600840688:assumed-role/Admin/llucc-Isengard is not authorized to perform: s3:PutBucketPolicy on resource: "arn:aws:s3:::awsconfigconforms-crcd-cirt-571600840688" because public policies are blocked by the BlockPublicPolicy block public access setting.
              # using a specific account's service-linked role ARN would not work correctly for organization-wide AWS Config Conformance Packs [1]. The policy needs to allow access from Config service-linked roles across all accounts in the organization.
              # AWS: !Sub arn:aws:iam::${AWS::AccountId}:role/aws-service-role/config-conforms.amazonaws.com/AWSServiceRoleForConfigConforms
            Condition:
              StringEquals:
                aws:PrincipalOrgID: ${aws:PrincipalOrgID}
              ArnLike:
                aws:PrincipalArn: "arn:aws:iam::*:role/aws-service-role/config-conforms.amazonaws.com/AWSServiceRoleForConfigConforms"
              Bool:
                aws:SecureTransport: true
          - Sid: AWSConfigConformsReadWriteBucket
            Action:
              - s3:PutObject
              - s3:GetObject
            Effect: Allow
            Resource: !Sub ${DeliveryS3Bucket.Arn}/*
            Principal:
              Service: config.amazonaws.com
            Condition:
              StringEquals:
                aws:PrincipalOrgID: ${aws:PrincipalOrgID}
              ArnLike:
                aws:PrincipalArn: "arn:aws:iam::*:role/aws-service-role/config-conforms.amazonaws.com/AWSServiceRoleForConfigConforms"
              Bool:
                aws:SecureTransport: true

  OrganizationConformancePack:
    Type: 'AWS::Config::OrganizationConformancePack'
    Properties:
      OrganizationConformancePackName: 'crcd-cirt-security-recommendations'
      DeliveryS3Bucket: !Ref DeliveryS3Bucket
      ExcludedAccounts: !Ref ExcludedAccounts
      TemplateBody: |
        ConformancePackName: crcd-cirt-security-recommendations
        Description: "Conformance pack for comprehensive security controls recommended by AWS Customer Incident Response Team (CIRT)"

        Parameters:  # Add parameters section at the top level
          ApiGatewayEndpointTypes:
            Type: String
            Default: "PRIVATE,REGIONAL"
            Description: "Allowed API Gateway endpoint types (EDGE, REGIONAL, PRIVATE)"

        Resources:
          RootAccountHardwareMFAEnabled:
            Type: AWS::Config::ConfigRule
            Properties:
              ConfigRuleName: crcd-cirt-root-account-hardware-mfa-enabled
              Source:
                Owner: AWS
                SourceIdentifier: ROOT_ACCOUNT_HARDWARE_MFA_ENABLED
              MaximumExecutionFrequency: TwentyFour_Hours

          RootAccountMFAEnabled:
            Type: AWS::Config::ConfigRule
            Properties:
              ConfigRuleName: crcd-cirt-root-account-mfa-enabled
              Source:
                Owner: AWS
                SourceIdentifier: ROOT_ACCOUNT_MFA_ENABLED
              MaximumExecutionFrequency: TwentyFour_Hours

          IAMRootAccessKeyCheck:
            Type: AWS::Config::ConfigRule
            Properties:
              ConfigRuleName: crcd-cirt-iam-root-access-key-check
              Source:
                Owner: AWS
                SourceIdentifier: IAM_ROOT_ACCESS_KEY_CHECK
              MaximumExecutionFrequency: TwentyFour_Hours

          IAMUserMFAEnabled:
            Type: AWS::Config::ConfigRule
            Properties:
              ConfigRuleName: crcd-cirt-iam-user-mfa-enabled
              Source:
                Owner: AWS
                SourceIdentifier: IAM_USER_MFA_ENABLED

          MFAEnabledForIAMConsoleAccess:
            Type: AWS::Config::ConfigRule
            Properties:
              ConfigRuleName: crcd-cirt-mfa-enabled-for-iam-console-access
              Source:
                Owner: AWS
                SourceIdentifier: MFA_ENABLED_FOR_IAM_CONSOLE_ACCESS

          AutoscalingLaunchConfigRequiresIMDSv2:
            Type: AWS::Config::ConfigRule
            Properties:
              ConfigRuleName: crcd-cirt-autoscaling-launchconfig-requires-imdsv2
              Source:
                Owner: AWS
                SourceIdentifier: AUTOSCALING_LAUNCH_CONFIG_PUBLIC_IP_DISABLED

          EC2IMDSv2Check:
            Type: AWS::Config::ConfigRule
            Properties:
              ConfigRuleName: crcd-cirt-ec2-imdsv2-check
              Source:
                Owner: AWS
                SourceIdentifier: EC2_IMDSV2_CHECK

          EC2LaunchTemplateIMDSv2Check:
            Type: AWS::Config::ConfigRule
            Properties:
              ConfigRuleName: crcd-cirt-ec2-launch-template-imdsv2-check
              Source:
                Owner: AWS
                SourceIdentifier: EC2_LAUNCH_TEMPLATE_IMDSV2_CHECK

          S3BucketPublicReadProhibited:
            Type: AWS::Config::ConfigRule
            Properties:
              ConfigRuleName: crcd-cirt-s3-bucket-public-read-prohibited
              Source:
                Owner: AWS
                SourceIdentifier: S3_BUCKET_PUBLIC_READ_PROHIBITED

          S3BucketPublicWriteProhibited:
            Type: AWS::Config::ConfigRule
            Properties:
              ConfigRuleName: crcd-cirt-s3-bucket-public-write-prohibited
              Source:
                Owner: AWS
                SourceIdentifier: S3_BUCKET_PUBLIC_WRITE_PROHIBITED

          S3AccessPointInVPCOnly:
            Type: AWS::Config::ConfigRule
            Properties:
              ConfigRuleName: crcd-cirt-s3-access-point-in-vpc-only
              Source:
                Owner: AWS
                SourceIdentifier: S3_ACCESS_POINT_IN_VPC_ONLY

          S3AccessPointPublicAccessBlocks:
            Type: AWS::Config::ConfigRule
            Properties:
              ConfigRuleName: crcd-cirt-s3-access-point-public-access-blocks
              Source:
                Owner: AWS
                SourceIdentifier: S3_ACCESS_POINT_PUBLIC_ACCESS_BLOCKS

          S3AccountLevelPublicAccessBlocks:
            Type: AWS::Config::ConfigRule
            Properties:
              ConfigRuleName: crcd-cirt-s3-account-level-public-access-blocks
              Source:
                Owner: AWS
                SourceIdentifier: S3_ACCOUNT_LEVEL_PUBLIC_ACCESS_BLOCKS

          S3AccountLevelPublicAccessBlocksPeriodic:
            Type: AWS::Config::ConfigRule
            Properties:
              ConfigRuleName: crcd-cirt-s3-account-level-public-access-blocks-periodic
              Source:
                Owner: AWS
                SourceIdentifier: S3_ACCOUNT_LEVEL_PUBLIC_ACCESS_BLOCKS_PERIODIC
              MaximumExecutionFrequency: TwentyFour_Hours

          S3BucketLevelPublicAccessProhibited:
            Type: AWS::Config::ConfigRule
            Properties:
              ConfigRuleName: crcd-cirt-s3-bucket-level-public-access-prohibited
              Source:
                Owner: AWS
                SourceIdentifier: S3_BUCKET_LEVEL_PUBLIC_ACCESS_PROHIBITED

          RedshiftUnrestrictedPortAccess:
            Type: AWS::Config::ConfigRule
            Properties:
              ConfigRuleName: crcd-cirt-redshift-unrestricted-port-access
              Source:
                Owner: AWS
                SourceIdentifier: REDSHIFT_CLUSTER_PUBLIC_ACCESS_CHECK

          RestrictedCommonPorts:
            Type: AWS::Config::ConfigRule
            Properties:
              ConfigRuleName: crcd-cirt-restricted-common-ports
              Source:
                Owner: AWS
                SourceIdentifier: RESTRICTED_INCOMING_TRAFFIC

          VPCSGOpenOnlyToAuthorizedPorts:
            Type: AWS::Config::ConfigRule
            Properties:
              ConfigRuleName: crcd-cirt-vpc-sg-open-only-to-authorized-ports
              Source:
                Owner: AWS
                SourceIdentifier: VPC_SG_OPEN_ONLY_TO_AUTHORIZED_PORTS

          VPCSGPortRestrictionCheck:
            Type: AWS::Config::ConfigRule
            Properties:
              ConfigRuleName: crcd-cirt-vpc-sg-port-restriction-check
              Source:
                Owner: AWS
                SourceIdentifier: VPC_SG_PORT_RESTRICTION_CHECK

          APIGWv2AccessLogsEnabled:
            Type: AWS::Config::ConfigRule
            Properties:
              ConfigRuleName: crcd-cirt-api-gwv2-access-logs-enabled
              Source:
                Owner: AWS
                SourceIdentifier: API_GW_EXECUTION_LOGGING_ENABLED

          APIGWv2AuthorizationTypeConfigured:
            Type: AWS::Config::ConfigRule
            Properties:
              ConfigRuleName: crcd-cirt-api-gwv2-authorization-type-configured
              Source:
                Owner: AWS
                SourceIdentifier: API_GWV2_AUTHORIZATION_TYPE_CONFIGURED

          APIGWAssociatedWithWAF:
            Type: AWS::Config::ConfigRule
            Properties:
              ConfigRuleName: crcd-cirt-api-gw-associated-with-waf
              Source:
                Owner: AWS
                SourceIdentifier: API_GW_ASSOCIATED_WITH_WAF

          APIGWCacheEnabledAndEncrypted:
            Type: AWS::Config::ConfigRule
            Properties:
              ConfigRuleName: crcd-cirt-api-gw-cache-enabled-and-encrypted
              Source:
                Owner: AWS
                SourceIdentifier: API_GW_CACHE_ENABLED_AND_ENCRYPTED
          
          APIGWEndpointTypeCheck: # We enforce certain endpoint types only - may not be everyone's use case, see https://docs.aws.amazon.com/config/latest/developerguide/api-gw-endpoint-type-check.html
            Type: AWS::Config::ConfigRule
            Properties:
              ConfigRuleName: crcd-cirt-api-gw-endpoint-type-check
              Source:
                Owner: AWS
                SourceIdentifier: API_GW_ENDPOINT_TYPE_CHECK
              InputParameters:
                endpointConfigurationTypes: ${ApiGatewayEndpointTypes}


          APIGWExecutionLoggingEnabled:
            Type: AWS::Config::ConfigRule
            Properties:
              ConfigRuleName: crcd-cirt-api-gw-execution-logging-enabled
              Source:
                Owner: AWS
                SourceIdentifier: API_GW_EXECUTION_LOGGING_ENABLED

          APIGWSSLEnabled:
            Type: AWS::Config::ConfigRule
            Properties:
              ConfigRuleName: crcd-cirt-api-gw-ssl-enabled
              Source:
                Owner: AWS
                SourceIdentifier: API_GW_SSL_ENABLED

          APIGWXRayEnabled:
            Type: AWS::Config::ConfigRule
            Properties:
              ConfigRuleName: crcd-cirt-api-gw-xray-enabled
              Source:
                Owner: AWS
                SourceIdentifier: API_GW_XRAY_ENABLED

Outputs:
  BucketName:
    Description: Name of the created S3 bucket
    Value: !Ref DeliveryS3Bucket
  BucketArn:
    Description: ARN of the created S3 bucket
    Value: !GetAtt DeliveryS3Bucket.Arn
