# Base file for the definition of the CRCD CIRT Conformance pack
# Naming conventions for ConfigRuleName:
# crcd-cirt-<lv1 and lv2 classification>-<rule name>
# lv1 will indicate: Initial Access, 2nd level TBC, 3rd level TBC
# lv2 will refine the classification within the level 1
#
# Current classification - the code in the rule name matches calculated fields and display names on Quick Suite
# Classification code | Lv1 Classification | Lv2 Classification
# crcd-cirt-ia-s3     | Initial Access     | S3 Protection
# crcd-cirt-ia-iam    | Initial Access     | IAM Protection
# crcd-cirt-ia-ec2    | Initial Access     | EC2 Protection
# crcd-cirt-ia-ra     | Initial Access     | Resource Access Protection


ConformancePackName: crcd-cirt-security-recommendations
Description: "Conformance pack for comprehensive security controls recommended by AWS Customer Incident Response Team (CIRT)"

# Parameters:  # Add parameters section at the top level, when you have parameters

Resources:

  # ------------------------------------------------------------------------------------------
  # Initial Access
  # ------------------------------------------------------------------------------------------
  RootAccountMFAEnabled:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: crcd-cirt-ia-iam-root-account-mfa-enabled
      Source:
        Owner: AWS
        SourceIdentifier: ROOT_ACCOUNT_MFA_ENABLED
      MaximumExecutionFrequency: TwentyFour_Hours

  IAMRootAccessKeyCheck:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: crcd-cirt-ia-iam-iam-root-access-key-check
      Source:
        Owner: AWS
        SourceIdentifier: IAM_ROOT_ACCESS_KEY_CHECK
      MaximumExecutionFrequency: TwentyFour_Hours

  IAMUserMFAEnabled:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: crcd-cirt-ia-iam-iam-user-mfa-enabled
      Source:
        Owner: AWS
        SourceIdentifier: IAM_USER_MFA_ENABLED

  MFAEnabledForIAMConsoleAccess:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: crcd-cirt-ia-iam-mfa-enabled-for-iam-console-access
      Source:
        Owner: AWS
        SourceIdentifier: MFA_ENABLED_FOR_IAM_CONSOLE_ACCESS

  AutoscalingLaunchConfigRequiresIMDSv2:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: crcd-cirt-ia-ec2-autoscaling-launchconfig-requires-imdsv2
      Source:
        Owner: AWS
        SourceIdentifier: AUTOSCALING_LAUNCH_CONFIG_PUBLIC_IP_DISABLED

  EC2IMDSv2Check:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: crcd-cirt-ia-ec2-ec2-imdsv2-check
      Source:
        Owner: AWS
        SourceIdentifier: EC2_IMDSV2_CHECK

  EC2LaunchTemplateIMDSv2Check:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: crcd-cirt-ia-ec2-ec2-launch-template-imdsv2-check
      Source:
        Owner: AWS
        SourceIdentifier: EC2_LAUNCH_TEMPLATE_IMDSV2_CHECK

  S3BucketPublicReadProhibited:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: crcd-cirt-ia-s3-s3-bucket-public-read-prohibited
      Source:
        Owner: AWS
        SourceIdentifier: S3_BUCKET_PUBLIC_READ_PROHIBITED

  S3BucketPublicWriteProhibited:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: crcd-cirt-ia-s3-s3-bucket-public-write-prohibited
      Source:
        Owner: AWS
        SourceIdentifier: S3_BUCKET_PUBLIC_WRITE_PROHIBITED

  S3AccessPointInVPCOnly:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: crcd-cirt-ia-s3-s3-access-point-in-vpc-only
      Source:
        Owner: AWS
        SourceIdentifier: S3_ACCESS_POINT_IN_VPC_ONLY

  S3AccessPointPublicAccessBlocks:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: crcd-cirt-ia-s3-s3-access-point-public-access-blocks
      Source:
        Owner: AWS
        SourceIdentifier: S3_ACCESS_POINT_PUBLIC_ACCESS_BLOCKS

  S3AccountLevelPublicAccessBlocks:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: crcd-cirt-ia-s3-s3-account-level-public-access-blocks
      Source:
        Owner: AWS
        SourceIdentifier: S3_ACCOUNT_LEVEL_PUBLIC_ACCESS_BLOCKS

  S3AccountLevelPublicAccessBlocksPeriodic:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: crcd-cirt-ia-s3-s3-account-level-public-access-blocks-periodic
      Source:
        Owner: AWS
        SourceIdentifier: S3_ACCOUNT_LEVEL_PUBLIC_ACCESS_BLOCKS_PERIODIC
      MaximumExecutionFrequency: TwentyFour_Hours

  S3BucketLevelPublicAccessProhibited:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: crcd-cirt-ia-s3-s3-bucket-level-public-access-prohibited
      Source:
        Owner: AWS
        SourceIdentifier: S3_BUCKET_LEVEL_PUBLIC_ACCESS_PROHIBITED

  VPCSGPortRestrictionCheck:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: crcd-cirt-ia-ra-vpc-sg-port-restriction-check
      Source:
        Owner: AWS
        SourceIdentifier: VPC_SG_PORT_RESTRICTION_CHECK

  # ------------------------------------------------------------------------------------------
  # 2nd level TBC
  # ------------------------------------------------------------------------------------------

  # ------------------------------------------------------------------------------------------
  # 3rd level TBC
  # ------------------------------------------------------------------------------------------
